In [5]:
import numpy as np

In [6]:
#  1. How to Creating a 3x3 Identity Matrix with Float Data Type?
a=np.identity(3,dtype=float)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 2. Create a 1D Array with Random Values between 0 and 1.
randon_array=np.random.rand(5)
print(randon_array)


[0.0049988  0.10617844 0.82386562 0.63357663 0.32005097]


In [8]:
# 3. Create a 2D Array with Random Integer Values.
randon_array=np.random.randint(10,size=(3,3))
print(randon_array)


[[7 2 3]
 [5 2 6]
 [1 9 1]]


In [9]:
# 4. Creating an Array Using a Custom Function.
def custom_function(i,j):
    return i+j
custom_array=np.fromfunction(custom_function,(3,3))
print(custom_array)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [10]:
# 5. Reshaping a 1D Array into a 2D Array .
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,4)
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [11]:
# 6.How to Creating a 3x3 Array of Ones?
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# 7. How to get the common items between two pythons NumPy?
# Input: a = np. array ([1,2,3,2,3,4,3,4,5,6])
       # b = np. array ([7,2,10,2,7,4,9,4,9,8])
a=common_items=np.array([1,2,3,2,3,4,3,4,5,6])
b=common_items=np.array([7,2,10,2,7,4,9,4,9,8])
common_items=np.intersect1d(a,b)
print(common_items)



[2 4]


In [13]:
# 8. From array a remove all items present in array b
#  Input: a = np. array ([1,2,3,4,5])
#         b = np. array ([5,6,7,8,9])
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
result=np.setdiff1d(a,b)
print(result)

[1 2 3 4]


In [14]:
# 9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements.
#  a = np. arrange (15)
a=np.arange(15)
np.set_printoptions(threshold=6)
print(a)


[ 0  1  2 ... 12 13 14]


In [15]:
# 10. Drop all nan values from a 1D NumPy array
#  Input: np. array ([1,2,3, np.nan,5,6,7, np.nan])
np.array([1,2,3, np.nan,5,6,7, np.nan])
a=np.array([1,2,3, np.nan,5,6,7, np.nan])
a[~np.isnan(a)]


array([1., 2., 3., 5., 6., 7.])

In [16]:
# 11. Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(a)

b = np.arange(1, 21).reshape(4, 5)
print(b)

[ 1  2  3 ... 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
# 12. Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type.
# Change its data type to float64 and verify the change.
r=np.array([[[2, 3, 4], [2, 3, 4]], [[2, 3, 4], [2, 3, 4]]])
print(r.shape)
print(r.size)
print(r.ndim)
print(r.dtype)
r=r.astype(np.float64)
print(r.dtype)




(2, 2, 3)
12
3
int64
float64


In [18]:
# 13. Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel ().
#  Verify that the flattened array matches the original.
a=np.arange(12)
print(a)
b=a.reshape(3,4)
print(b)
c=b.ravel()
print(c)


[ 0  1  2 ...  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2 ...  9 10 11]


In [19]:
# 14. Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division.
#  Explain the behavior when dividing by zero.
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [20]:
# 15. Create a 2D array of shape (3, 1) and a 1D array of length 3.
#  Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario.
b=np.array([[2],[4],[6]])
print(b)
c=np.array([1,3,5])
print(c)
d=b+c
print(d)


[[2]
 [4]
 [6]]
[1 3 5]
[[ 3  5  7]
 [ 5  7  9]
 [ 7  9 11]]


In [21]:
# 16. Generate a random 2D array of integers between 0 and 10.
#  Use conditional operators to create a Boolean mask identifying elements greater than 5.
#  Replace all elements greater than 5 with the value 5.
np.random.seed(42)
a=np.random.randint(0,11,size=(3,3))
print(a)
mask=a>5
print(mask)
a[mask]=5
print(a)


[[ 6  3 10]
 [ 7  4  6]
 [ 9  2  6]]
[[ True False  True]
 [ True False  True]
 [ True False  True]]
[[5 3 5]
 [5 4 5]
 [5 2 5]]


In [41]:
# 17. create a 4x4 array of random integers, use indexing and slicing to extract:
#  o The entire second row
#  o The last column
#  o The subarray consisting of the first two rows and first two columns.

a = np.random.randint(0, 100, size=(4, 4))
print("Original Array:\n",a)

second_row = a[1, :]
print("\nSecond row:", second_row)

last_column = a[:, -1]
print("\nLast column:", last_column)

subarray = a[:2, :2]
print("\nSubarray (first two rows, first two columns):\n", subarray)

Original Array:
 [[35 49  3  1]
 [ 5 53  3 53]
 [92 62 17 89]
 [43 33 73 61]]

Second row: [ 5 53  3 53]

Last column: [ 1 53 89 61]

Subarray (first two rows, first two columns):
 [[35 49]
 [ 5 53]]


In [23]:
# 18. Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each area.
     # 1. Exploratory Data Analysis (EDA):
ages = np.array([25, 30, 22, 40, 35, 28, 60, 45])

mean_age = np.mean(ages)
median_age = np.median(ages)
std_age = np.std(ages)

print("Mean age:", mean_age)
print("Median age:", median_age)
print("Standard Deviation:", std_age)

      # 2. Artificial Intelligence (AI)
utility_scores = np.array([0.4, 0.7, 0.6, 0.8, 0.5])
best_move = np.argmax(utility_scores)
print("Best move index:", best_move)
print("Best move utility:", utility_scores[best_move])

      #  3. Machine Learning (ML)
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
X = np.vstack([np.ones(len(x)), x]).T
w = np.linalg.inv(X.T @ X) @ X.T @ y
print("Linear regression weights:", w)

      # 4. Deep Learning (DL)
inputs = np.array([[1.0, 2.0, -1.0],
                   [0.5, 0.0, 2.0]])
weights = np.array([[0.2, -0.5],
                    [0.3, 0.8],
                    [-0.6, 0.1]])
biases = np.array([0.1, -0.2])
z = inputs @ weights + biases
output = np.maximum(0, z)
print("Output of dense layer with ReLU:")
print(output)

Mean age: 35.625
Median age: 32.5
Standard Deviation: 11.67194820927509
Best move index: 3
Best move utility: 0.8
Linear regression weights: [2.2 0.6]
Output of dense layer with ReLU:
[[1.5 0.8]
 [0.  0. ]]


In [24]:
# 19. Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors.
#  Verify the eigenvalues by reconstructing the matrix.

np.random.seed(42)

A = np.random.rand(4, 4)
print("Original Matrix A:\n", A)


eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors (columns):\n", eigenvectors)


D = np.diag(eigenvalues)
V = eigenvectors
V_inv = np.linalg.inv(V)

A_reconstructed = V @ D @ V_inv


print("\nReconstructed Matrix A:\n", A_reconstructed)


print("\nAre A and reconstructed A close?", np.allclose(A, A_reconstructed))


Original Matrix A:
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]

Eigenvalues:
 [ 1.83720612+0.j         -0.39432133+0.55229552j -0.39432133-0.55229552j
 -0.31403981+0.j        ]

Eigenvectors (columns):
 [[ 0.64723702+0.j          0.58357969+0.j          0.58357969-0.j
  -0.18805166+0.j        ]
 [ 0.29851455+0.j         -0.25203329+0.49664672j -0.25203329-0.49664672j
  -0.60580025+0.j        ]
 [ 0.55766099+0.j         -0.07578653+0.19548415j -0.07578653-0.19548415j
   0.70586228+0.j        ]
 [ 0.4254263 +0.j         -0.25658199-0.48935063j -0.25658199+0.48935063j
   0.31527935+0.j        ]]

Reconstructed Matrix A:
 [[0.37454012-7.29090257e-17j 0.95071431-1.33340074e-16j
  0.73199394+3.50581434e-17j 0.59865848+3.09976655e-17j]
 [0.15601864+3.07479745e-17j 0.15599452-7.20098652e-17j
  0.05808361-1.96458082e-17j 0.86617615+5.12933652e-18j]
 [

In [25]:
# 20. Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array.
# Flatten it back into a 1D array and compare the flattened array with the original.
original_array = np.arange(27)
print("Original 1D array:\n", original_array)

array_3d = original_array.reshape((3, 3, 3))
print("\nReshaped 3D array (3x3x3):\n", array_3d)


flattened_array = array_3d.flatten()
print("\nFlattened array:\n", flattened_array)


are_equal = np.array_equal(original_array, flattened_array)
print("\nAre the original and flattened arrays equal?", are_equal)


Original 1D array:
 [ 0  1  2 ... 24 25 26]

Reshaped 3D array (3x3x3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened array:
 [ 0  1  2 ... 24 25 26]

Are the original and flattened arrays equal? True


In [38]:
# 21. create and Perform matrix multiplication of two 2D arrays using np.dot () and @.
#  Compare the results and performance of both methods using a large dataset.
newarr1 = np.array([[1, 2], [3, 4]])
newarr2 = np.array([[5, 6], [7, 8]])

result_dot = np.dot(newarr1, newarr2)
result_at = newarr1 @ newarr2
print("Result using np.dot():\n", result_dot)
print("\nResult using @ operator:\n", result_at)

Result using np.dot():
 [[19 22]
 [43 50]]

Result using @ operator:
 [[19 22]
 [43 50]]


In [27]:
# 22. Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1).
# Perform an element-wise operation using broadcasting and explain the result.
# Use np. new axis to achieve the same result without broadcasting.
A = np.array([[[1, 2, 3, 4]],
              [[5, 6, 7, 8]]])

B = np.array([[10],
              [20],
              [30],
              [40]])
B_T = B.T


result_broadcast = A + B_T

print("Broadcasted result:\n", result_broadcast)
print("Shape:", result_broadcast.shape)

B_reshaped = B.T[np.newaxis, :, :]


result_manual = A + B_reshaped

print("\nManual reshape with np.newaxis:\n", result_manual)
print("Shape:", result_manual.shape)

Broadcasted result:
 [[[11 22 33 44]]

 [[15 26 37 48]]]
Shape: (2, 1, 4)

Manual reshape with np.newaxis:
 [[[11 22 33 44]]

 [[15 26 37 48]]]
Shape: (2, 1, 4)


In [28]:
# 23. Generate a 2D array of random floats between 0 and 1.
# Use conditional operators to create a Boolean mask for values less than 0.5.
# Replace these values with their squares and leave the rest unchanged.

np.random.seed(42)
arr = np.random.rand(4, 5)

print("Original Array:\n", arr)

mask = arr < 0.5


arr[mask] = arr[mask] ** 2

print("\nModified Array (values < 0.5 squared):\n", arr)

Original Array:
 [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]

Modified Array (values < 0.5 squared):
 [[1.40280301e-01 9.50714306e-01 7.31993942e-01 5.98658484e-01
  2.43418162e-02]
 [2.43342904e-02 3.37370600e-03 8.66176146e-01 6.01115012e-01
  7.08072578e-01]
 [4.23721405e-04 9.69909852e-01 8.32442641e-01 4.50878979e-02
  3.30603187e-02]
 [3.36372142e-02 9.25633424e-02 5.24756432e-01 1.86576499e-01
  8.48144121e-02]]


In [35]:
# 24. create a 5x5 array of sequential integers, use slicing to:
# o Extract the diagonal elements
# o Replace the elements of the middle row with zeros
# o Flip the array vertically and horizontally

newarr=np.arange(25).reshape(5,5)
print(newarr)

newarr_diagonal=np.diag(newarr)
print(newarr_diagonal)

newarr[2]=np.zeros(5)
print(newarr)

newarrFlip=np.flip(newarr)
print(newarrFlip)

newarrFlipH=np.flip(newarr,axis=1)
print(newarrFlipH)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  6 12 18 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[24 23 22 21 20]
 [19 18 17 16 15]
 [ 0  0  0  0  0]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [ 0  0  0  0  0]
 [19 18 17 16 15]
 [24 23 22 21 20]]


In [30]:
# 25. Create a 4D array of shape (2, 3, 4, 5) with random integers.
# Use advanced slicing to extract a subarray and compute the mean along a specified axis.

np.random.seed(42)
arr = np.random.randint(0, 100, size=(2, 3, 4, 5))

print("Original array shape:", arr.shape)


subarray = arr[0, :, 0:2, :]
print("\nSubarray shape:", subarray.shape)


mean_result = np.mean(subarray, axis=2)
print("\nMean along axis=2 of subarray:\n", mean_result)

Original array shape: (2, 3, 4, 5)

Subarray shape: (3, 2, 5)

Mean along axis=2 of subarray:
 [[57.6 67.2]
 [35.  57.8]
 [46.  37.2]]


In [31]:
# 26. Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40).
# Discuss the impact on the array's shape, size, and dimensionality.

arr = np.arange(200).reshape(10, 20)
print("Original shape:", arr.shape)

reshaped_1 = arr.reshape(20, 10)
print("Reshaped to (20, 10):", reshaped_1.shape)

reshaped_2 = arr.reshape(5, 40)
print("Reshaped to (5, 40):", reshaped_2.shape)



Original shape: (10, 20)
Reshaped to (20, 10): (20, 10)
Reshaped to (5, 40): (5, 40)


In [32]:
# 27. Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations.

np.random.seed(42)
A = np.random.rand(100, 50)

print("Original shape:", A.shape)

A_reshaped = A.reshape(50, 100)
print("\nReshaped shape:", A_reshaped.shape)

A_unraveled = A_reshaped.ravel()
print("\nUnraveled shape:", A_unraveled.shape)



Original shape: (100, 50)

Reshaped shape: (50, 100)

Unraveled shape: (5000,)


In [33]:
# 28. Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero.
# Verify the result

np.random.seed(42)
matrix = np.random.randint(1, 100, size=(6, 6))

print("Original Matrix:\n", matrix)

upper_tri_matrix = np.triu(matrix)

print("\nModified Matrix (lower triangle set to 0):\n", upper_tri_matrix)

Original Matrix:
 [[52 93 15 72 61 21]
 [83 87 75 75 88 24]
 [ 3 22 53  2 88 30]
 [38  2 64 60 21 33]
 [76 58 22 89 49 91]
 [59 42 92 60 80 15]]

Modified Matrix (lower triangle set to 0):
 [[52 93 15 72 61 21]
 [ 0 87 75 75 88 24]
 [ 0  0 53  2 88 30]
 [ 0  0  0 60 21 33]
 [ 0  0  0  0 49 91]
 [ 0  0  0  0  0 15]]
